# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LightController (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LightController (iOS)
  pod 'CocoaMQTT'
  pod 'SwiftMQTT'

end

target 'LightController (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LightController (macOS)
  pod 'CocoaMQTT'
  pod 'SwiftMQTT'

end
